finnishtransportagency/dvk

.editorconfig
.eslintignore
.eslintrc.json
.prettierrc
package-lock.json
package.json
squat/.eslintignore
squat/.eslintrc.json
squat/.prettierrc
squat/package-lock.json
squat/package.json
squat/src/App.tsx
squat/src/i18n.tsx
squat/src/index.tsx
squat/src/setupTests.ts
src/App.tsx
src/components/Map.tsx
src/i18n.tsx
src/pages/Home.tsx
src/serviceWorkerRegistration.ts
src/setupTests.ts

Squat project files not fixed since would cause too many merge conflicts.

ESLint & Prettier config

---

squat/cdk/.gitignore
squat/cdk/lib/lambda/router/squatRequestRouter.js
squat/cdk/lib/squat-site.ts

* added cf function for squat behavior, removed obsolete cf settings

feat: cloudfront function router for squat

---

cdk/lib/dvk-backend.ts
cdk/lib/squat-site.ts

* added automated deletion policy to non-permanent envs

feat: DVK-144-turhien-AWS-resurssien-poisto 

---

squat/src/components/Environment.tsx
squat/src/components/Modal.tsx
squat/src/components/RadioSelectField.tsx
squat/src/theme/squat.css

* new modal css, radioselect props modal size

feat: DVK-247-modal-changes

---

cdk/lib/lambda/router/squatRequestRouter.js
cdk/lib/squat-site.ts

* remove auth from squat router, remove auth lambda from dvk behaviour

feat: DVK-288 authentication changes

---

squat/src/components/Calculations.tsx
squat/src/components/Modal.tsx
squat/src/theme/squat.css

* add onDidDismiss handler for closing outside modal, minor styling and i18 fixes

fix: DVK-289 modal fixes 

---

Dockerfile
cdk/lib/dvk-build-image-stack.ts
cdk/lib/dvk-pipeline.ts
cdk/lib/squat-pipeline.ts

* install aws cli to build dvk image, use image in pipelines for simple aws tasks

feat: DVK-206 cicd nopeutus

---

cdk/lib/lambda/environment.ts
cdk/lib/lambda/message-handler.ts
cdk/lib/pipeline-messaging.ts

* add new rocket chat endpoint, change credential handling, add information to chat message

feat: DVK-325 aws notifikaatiot

---

squat/src/components/Vessel.tsx

* remove col size from vessel profile to fix printing

fix: DVK-295 aluksen profiilin tulostuksen korjaus

---

squat/package-lock.json
squat/package.json
squat/src/components/Calculations.tsx
squat/src/components/Environment.tsx
squat/src/components/InfoAccordion.css
squat/src/components/InfoAccordion.tsx
squat/src/components/Modal.tsx
squat/src/components/SectionTitle.tsx
squat/src/components/Squat.tsx
squat/src/locales/en/translation.json
squat/src/locales/fi/translation.json
squat/src/locales/sv/translation.json

* accordion ei pikselintarkasti ui-suunnitelman mukainen, koska perumuodossaan ionic tarjoilee valmiina käytettävän iconin vain joko itemin alkuun tai loppuun (kauaksi tekstistä).
* trans-komponenttia käytin, jotta saan helposti html-muotoilun pitkiin teksteihin pilkkomatta sitä osiin

feature: DVK-157 yleisesittely-accordion, uudet tekstit ja info-laatikot

---

.eslintignore
cdk/lib/lambda/router/dvkRequestRouter.js
cdk/lib/squat-site.ts

* add dvk app routing, remove obsolete auth string replacement

feat: DVK-367 vaylakortit routing

---

squat/src/components/TitleBar.tsx
squat/src/locales/en/translation.json
squat/src/locales/fi/translation.json
squat/src/locales/sv/translation.json

* add alt and title texts to logo

fix: DVK-396 väyläviraston logon tekstivastineet

---

squat/src/components/Modal.tsx
squat/src/components/SectionTitle.tsx
squat/src/locales/en/translation.json
squat/src/locales/fi/translation.json
squat/src/locales/sv/translation.json

* add aria-labels and titles to section titles and modals

fix: DVK-398 tekstivastineita ikoneille

---

squat/src/components/InfoAccordion.css
squat/src/components/InfoAccordion.tsx

* add dvk styles for accordion

fix: DVK-372 Squatin yleinen accordion

---

squat/src/components/DataTableTitleColumn.tsx
squat/src/components/Environment.tsx
squat/src/components/InputField.tsx
squat/src/components/Label.tsx
squat/src/components/RadioSelectField.tsx
squat/src/components/Squat.tsx
squat/src/components/SquatChart.tsx
squat/src/components/SquatDataTable.css
squat/src/components/Vessel.tsx
squat/src/pages/Home.tsx
squat/src/theme/squat.css

* vaihdettu < strong > < b > < small > ja < h > headerien tilalle tyylejä
* lisätty arialabeleita ja tekstivastineita (title) ikoneille ja ryhmille
* siirretty yläpalkki ionheader elementiksi, jolloin sivun landmarkit ovat < banner > < main > ja < contentinfo >
* vaihdettu virheilmoituksille kolmio-ikoni
* lisätietomerkit siirretty tekstin kylkeen
* squat-kuvaajan barrass viivan väri vaihdettu

Fix: DVK-399...408 squat saavutettavuus korjauksia

---

squat/src/components/Calculations.tsx
squat/src/components/Label.tsx
squat/src/components/Modal.tsx
squat/src/components/RadioSelectField.tsx
squat/src/theme/squat.css

* add outline-only focus style to radio items and info-buttons
* remove calculations info-button away from inside h2 element

feat: DVK-403 kohdistustyylit ja kohdistaminen

---

squat/src/components/LabelField.tsx

change labelfield warning icon

fix: DVK-407 labelfield warning icons

---

squat/src/components/SquatChart.tsx

feat: DVK-410 squat kuvaajan poisto ruudunlukijalta

---

squat/src/locales/en/translation.json
squat/src/locales/fi/translation.json
squat/src/locales/sv/translation.json

* add unicode subscript 'nh' to froude translations

fix: DVK-290 Squat taulukon laskentasymbolit

---

squat/src/components/SquatDataTable.tsx
squat/src/locales/en/translation.json
squat/src/locales/fi/translation.json
squat/src/locales/sv/translation.json

fix: DVK-370 squat table translations

---

squat/src/App.tsx
squat/src/locales/en/translation.json
squat/src/locales/fi/translation.json
squat/src/locales/sv/translation.json

* add dynamic document title and metadata

feat: DVK-423 localized metadata

---

package-lock.json
package.json
src/App.tsx
src/components/DvkMap.css
src/components/FairwayCard.tsx
src/components/FairwayCards.css
src/components/FairwayCards.tsx
src/components/MainContent.tsx
src/components/PrintMap.tsx
src/components/mapControls/SearchbarControl.tsx
src/components/mapOverlays/LayerModal.tsx
src/locales/en/translation.json
src/locales/fi/translation.json
src/locales/sv/translation.json
src/pages/Home.tsx
src/theme/img/north_arrow.svg
src/theme/print.css
src/utils/common.ts

Creates image from all canvases (base map + layer canvas) with support for rotating map.

Feature/DVK-88, printable fairway card.

---

cdk/bin/dvk.ts
cdk/lib/config.ts
cdk/lib/dvk-pipeline.ts
cdk/lib/dvk-us-east.ts
cdk/lib/squat-site.ts
cdk/lib/ssm-parameter-reader.ts
cdk/package.json

add cloudfront wafconfig, us-east-stack and custom ssm parameter reader

feat: DVK-438 CloudFront WAF

---

cdk/bin/dvk.ts
cdk/lib/dvk-us-east.ts
cdk/lib/squat-site.ts

add parametrization to resources

fix: Cloudfront WAF cdk deployment

---

squat/src/components/PrintBar.tsx
squat/src/pages/Home.tsx
squat/src/theme/squat.css

add accessibility link, make printbar icons smaller

feat: accessibility link, icon changes

---

squat/.eslintrc.json
squat/src/components/Calculations.tsx
squat/src/components/InfoAccordion.css
squat/src/components/InputField.tsx
squat/src/components/Modal.tsx
squat/src/components/PrintBar.tsx
squat/src/components/RadioSelectField.tsx
squat/src/components/SelectField.tsx
squat/src/components/Vessel.tsx
squat/src/utils/calculations.tsx

* "Arrows functions as attributes will negatively impact performance in React. Each time the parent is rendered, the function will be re-created and trigger a render of the component causing excessive renders and more memory use. Wrapping the function in a useCallback hook will avoid additional renders."
* SonarLint was used for finding issues instead of Väyläpilvi SonarQube (9.12 vs 8.9 or so)

fix: DVK-541 squat sonarqube critical issues

---

squat/src/components/Calculations.tsx
squat/src/components/Environment.tsx
squat/src/components/SectionTitle.tsx
squat/src/components/SquatChart.css
squat/src/components/SquatChart.tsx
squat/src/components/SquatDataTable.tsx
squat/src/components/SquatHeader.tsx
squat/src/components/TitleBar.tsx
squat/src/components/Vessel.tsx
squat/src/pages/Home.tsx
squat/src/theme/squat.css

To test independently add and remove &baseURL=foobar, to test within Väylä's iframe download and save site and change iframe src to localhost

fix: DVK-589 squat upotustyylit

---

cdk/lib/dvk-pipeline.ts
src/components/popup/popup.css
src/components/popup/popup.ts

* mobiilissa estetty sormieleillä zoomaus popupien päällä
* yleisesti estetty popupin sulkeminen klikkaamalla sisältöä, jotta mahdollisuus copy&pasteen
* mikäli klikkaus popupin ulkopuolella, avataan uusi popup samantien mikäli featuren kohdalla, muuten pelkkä sulkeminen

feat: DVK-652 popup muutokset

---

cdk/lib/dvk-backend.ts

* remove lambda layer, add lifecycle rule

feat: DVK-746 s3 version bucket lifecycle

---

src/components/content/MainContent.tsx
src/components/mapControls/SearchbarControl.tsx

* haku enterillä (kartta + sivupaneeli)

feat: DVK-702 hakukentta saavutettavuus

---

src/components/SidebarMenu.css
src/components/SidebarMenu.tsx

* pidetään ja kierrätettään focus sivuvalikon sisällä
* footerin uusi rakenne ja tyyli
* lähdetiedot oikean painikkeen taakse

feat: DVK-698 sivuvalikon focuksen kierratys

---

src/components/mapOverlays/LayerItem.tsx
src/components/mapOverlays/LayerModal.css
src/components/mapOverlays/LayerModal.tsx
src/locales/en/translation.json
src/locales/fi/translation.json
src/locales/sv/translation.json

* tekstivastineet valinraruuduille
* fokuksen säilyminen (estä valintaruutujen uudelleen piirtyminen turhaan)
* karttasaovalintojen ryhmittely, lisää yleiset-osa, lisää ruudunlukijalle listan nimi

feat:DVK-710 karttatasovalintojen saavutettavuus

---

src/components/content/Content.css
src/components/content/FairwayCard.tsx
src/components/content/MainContent.tsx
src/components/content/MarineWarnings.tsx
src/components/content/SafetyEquipmentFaults.tsx
src/locales/en/translation.json
src/locales/fi/translation.json
src/locales/sv/translation.json

* lisaa ruudunlukijaa varten linkki paneelin paasisaltoon

feat: DVK-701 sivupaneeliin linkki ruudunlukijalle pääsisältöön

---

src/components/OfflineSupport.tsx
src/components/content/Paragraph.tsx

* iconeiden aria-hidden ja aria-label

feat: DVK-731 ikonien tekstivastineet tai piilotus ruudunlukijalta

---

cdk/lib/lambda/router/adminRequestRouter.js

* lisatty admin sovelluksen polkuja cloudfront function reititykseen

DVK-780 admin sivujen reititykset / suorat linkit ja sivun päivitys

---

src/components/SidebarMenu.tsx
src/components/content/FairwayCard.tsx
src/components/mapOverlays/CommonModal.tsx
src/locales/en/translation.json
src/locales/fi/translation.json
src/locales/sv/translation.json
src/theme/dvk.css

* add external link info for readers, hide it visually

feat: DVK-687 external link info for screen readers

---

src/components/SidebarMenu.tsx

feat: DVK-858 liikenteen asiakaspalvelun linkki

---

admin/package-lock.json
admin/package.json
package-lock.json
package.json
squat/package-lock.json
squat/package.json
src/components/content/MarineWarnings.tsx
src/components/content/SafetyEquipmentFaults.tsx
src/components/mapOverlays/LayerItem.tsx
src/components/mapOverlays/MapOverlays.tsx
src/locales/en/translation.json
src/locales/fi/translation.json
src/locales/sv/translation.json

* popup pois
* kaikki versionumerot -> 1.0.0
* mukaan samaan pr:ään vahingossa DVK-871, eli karttatasovalintojen varoitusten virhetilanteiden hallinta

feat: DVK-655 käynnistys-popupin poisto ja versionumerot

---

src/components/FeatureLoader.tsx
src/components/OfflineStatus.tsx
src/locales/fi/translation.json
src/locales/sv/translation.json
src/utils/common.ts
src/utils/constants.ts
src/utils/dataLoader.ts

* muuta cacheTime 48 tuntiin, lisaa ilmoitus offline-palkkiin 12 tunnin jalkeen

feat: DVK-827 offline tilan cache pidemmäksi

---

src/App.tsx

* tyhjennä query cache, kun sovelluksen versionumero vaihtuu

feat: DVK-897 query cachen tyhjennys

---

src/index.tsx

* add language detection url params

feat: DVK-927 linkitys suoraan kieliversioon

---

cdk/lib/dvk-us-east.ts

* disable body size restriction to allow picture uploads

fix: waf-kokorajoitus

---

squat/src/components/Calculations.tsx
squat/src/components/Environment.tsx

* lisää vallitseva vedenkorkeus
* mahdollista barrass-laskenta

feat: DVK-995 suppea squat muutokset

---

squat/src/components/Calculations.tsx

* show only straight UKC alerts in limited view

feat: DVK-1005 suppean tilan varoitukset

---

squat/src/components/Alert.tsx
squat/src/components/Vessel.tsx

* remove squat vessel warnings from limited view

fix: DVK-1005 fix vessel alerts in limited view

---

squat/src/components/Calculations.tsx
squat/src/components/Environment.tsx
squat/src/components/SquatChart.tsx
squat/src/components/SquatDataTable.tsx
squat/src/utils/calculations.test.tsx
squat/src/utils/calculations.tsx

* sonarquben raportoimat ongelmat korjattu

feat:DVK-1031 squat refaktorointi

---

src/components/layers.ts

* make renderbuffer bigger for arbors

fix: DVK-587 clickable harbor texts

---

src/components/layers.ts

fix: DVK-587 make quay texts clickable

---

src/components/content/SquatCalculator.tsx

fix: DVK-967 hide squat link from print

---

cdk/bin/bastion.sh

fix: DVK-1043 security hub fixes

---

cdk/package.json

* add analytics and monitoring scripts

fix: add missing npm scripts

---

cdk/lib/dvk-backend.ts
cdk/lib/pipeline-messaging.ts

fix: aws parameters and secrets layer update

---

cdk/fargate/Dockerfile
cdk/fargate/analyze.sh
cdk/lib/dvk-analytics-stack.ts
cdk/lib/dvk-build-image-stack.ts

* changed from amazonlinux2023 to amazonlinux2 for the geoip packages to be available (https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.2-AL2.html)

feat: DVK-1168 kayttotilastojen parannukset

---

admin/src/components/HarbourForm.tsx

* stop the submit if linked fairways

fix: DVK-1114 linked harbours state change 

---

cdk/lib/lambda/router/previewRequestRouter.js

reason: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-javascript-runtime-features.html

revert to previous preview router version

---

cdk/lib/lambda/api/login.ts

This reverts commit 079bedb75d74c53211a6fa5df2d7fa96883a93fb.

Revert "Log login headers"

---

cdk/lib/dvk-analytics-stack.ts

* add cpu and mem to match cpu

feat: DVK-1285 analytics ecs cpu update

---

cdk/bin/dvk.ts
cdk/lib/pipeline-lambda-vpc.ts
cdk/package.json

* add preview pipeline info to new lambda env, remove old lambda references

fix: DVK-1357 preview pipeline cicd

---

cdk/lib/dvk-scheduled-tests-pipeline.ts
cdk/lib/dvk-sonar-pipeline.ts
test/README.md

DVK-1287 robot image update to pipelines

---

cdk/lib/dvk-backend.ts

* replace depracated appsync api

feat: DVK-1313 cdk graphql schema deprecated

---

cdk/lib/squat-site.ts

* use api cache policies with permanent environments as well

DVK-1337 add cache policy to permanent environments

---

cdk/lib/squat-site.ts

* add dev behavior for github webhooks

DVK-1431: fix GitHub webhook

---

cdk/bin/bastion.sh

DVK-1375 bastion update

---

admin/package-lock.json
admin/package.json
cdk/package-lock.json
cdk/package.json
package-lock.json
package.json
squat/package-lock.json
squat/package.json

DVK-1384 update version to 1.15.0

---

cdk/fargate/analyze.sh
cdk/lib/dvk-analytics-stack.ts
cdk/lib/dvk-build-image-stack.ts

* make root filesystem read-only
* add an external filesystem for file copy and report generation

DVK-1377 analytics ecs task root access

---

cdk/lib/dvk-feature-pipeline.ts
cdk/lib/dvk-sonar-pipeline.ts

* remove unnecessary privileged mode from build projects not used for creating docker images

DVK-1376 remove privileged modes

---

admin/package-lock.json
admin/package.json
cdk/package-lock.json
cdk/package.json
package-lock.json
package.json
squat/package-lock.json
squat/package.json

DVK-1492 update version numbers

---

cdk/bin/images.sh

* add shell script for removing old ecr images
Check JIRA-ticket for instructions and comments

DVK-1406 ecr image cleanup

---

src/components/content/fairwayCard/AreaInfoListItem.tsx

* fix name after it was reverted to old style accidentally in another ticket

fix: DVK-1454 fix special area name

---

src/App.tsx
src/components/OfflineStatus.tsx
src/components/PrintMap.tsx
src/components/content/fairwayCard/FairwayCardHeader.tsx
src/components/mapOverlays/LayerModal.tsx

* add onbeforeprint event listener

DVK-1481 dynamic print image generation change

---

cdk/lib/dvk-backend.ts
cdk/lib/lambda/graphql/lambdaFunctions.ts

* add appsync api cache instance and resolver cache config

DVK-1504 GraphQL cache

---

cdk/lib/lambda/api/pilotRoutes.ts
cdk/lib/lambda/db/fairwayCardDBModel.ts
cdk/lib/lambda/db/harborDBModel.ts

Reverts finnishtransportagency/dvk#1024

Revert "HOTFIX: DVK-1535 - scan all entries using last evaluated key"

---

cdk/lib/lambda/db/fairwayCardDBModel.ts
cdk/lib/lambda/db/harborDBModel.ts

* HOTFIX: DVK-1535
* seaLevel fix

HOTFIX: DVK-1535 - scan all entries using last evaluated key (#1026)

---

src/components/content/Breadcrumb.tsx

* add href for breadcrumbs with full path

DVK-1521 breadcrumb href

---

admin/src/components/NotificationModal.tsx
admin/src/components/form/SectionHeader.tsx
admin/src/components/form/SelectWithCustomDropdown.tsx
admin/src/components/form/fairwayCard/NotificationSection.tsx
admin/src/locales/en/translation.json
admin/src/locales/fi/translation.json
admin/src/locales/sv/translation.json

UseTransElement käytetty modaalissa ilman i18nkey:tä, jolloin p-elementti muodostetaan, mutta teksti on undefined. Käytetään ehtona p-elementin näyttämiselle pelkkää i18nkey:tä.

DVK-1553 Remove undefined trans element from modal

---

cdk/lib/dvk-scheduled-tests-pipeline.ts

* drop run rate to lower data transfer etc

change prod testing schedule to lower data transfer

---

cdk/bin/datasync.ts
cdk/lib/dvk-sonar-pipeline.ts

fix: update robot environment tables

---

cdk/bin/bastion.sh

DVK-1567 bastion update

---

cdk/lib/dvk-feature-pipeline.ts

* add new default github credential provider to dev

fix: feature test build projects credentials

---

cdk/bin/picturemigration.ts

DVK-1621 picture migration fix

---

cdk/fargate/analyze.sh

* add option to input report year+month, remove previously downloaded files

DVK-1642 fix analytics report

---

cdk/lib/dvk-analytics-stack.ts
cdk/lib/dvk-build-image-stack.ts

DVK-1642 fix analytics image version

---

cdk/lib/dvk-backend.ts
cdk/lib/lambda/api/apiLambdaFunctions.ts
cdk/lib/lambda/graphql/lambdaFunctions.ts

* raise default lambda memory, add memory and timeout parameters for graphql/api lamdas

DVK-1651 lambdojen resurssien lisays ja parametrisointi

---

cdk/lib/lambda/api/ibnet.ts
cdk/lib/lambda/api/login.ts
cdk/lib/lambda/auth/authFunction.js
cdk/lib/lambda/db/modelMapper.ts
cdk/lib/lambda/graphql/mutation/saveFairwayCard-handler.ts
cdk/lib/lambda/graphql/query/fairwayCardsAndHarbors-handler.ts
cdk/lib/lambda/graphql/query/marineWarnings-handler.ts
cdk/lib/lambda/router/adminRequestRouter.js
cdk/lib/lambda/router/dvkRequestRouter.js
cdk/lib/lambda/router/previewRequestRouter.js
cdk/lib/lambda/router/replaceFunction.js
cdk/lib/lambda/router/squatRequestRouter.js
cdk/lib/lambda/util.ts
cdk/lib/lambda/webhook-handler.ts

Fixed all 19 notifications from https://sonarqube.vaylapilvi.fi/component_measures?metric=violations&selected=DVK-main%3Acdk%2Flib%2Flambda&id=DVK-main
In Javascript files, used let (anot const) to replace var to reduce the risk

DVK-1616 : CDK SonarLint corrections

---

Dockerfile
cdk/lib/admin-pipeline.ts
cdk/lib/dvk-build-image-stack.ts
cdk/lib/dvk-feature-pipeline.ts
cdk/lib/dvk-pipeline.ts
cdk/lib/preview-pipeline.ts
cdk/lib/squat-pipeline.ts

* change base image 
* modify python installations to virtual environment

DVK-1619 buildimage

---

cdk/lib/squat-site.ts

DVK-1622 jwt token

---

admin/src/components/ImageModal.tsx
admin/src/components/pictures/ExtMapControls.tsx
admin/src/components/pictures/PrintImages.tsx

Small check to prevent uploading files in readonly or disabled mode

DVK-1560 - check state for uploading picture from Map control

---

src/components/mapOverlays/CommonModal.tsx

* fix feedback textarea state saving

fix: DVK-1659 palautelomake

---

src/components/ForecastTable.tsx
src/components/content/Forecast.css
src/components/content/ForecastContainer.tsx
src/components/content/ForecastLegend.tsx
src/components/popup/ForecastPopupContent.tsx
src/locales/en/translation.json
src/locales/fi/translation.json
src/locales/sv/translation.json

Created a new component Forecast legend, as its needed in 2 places, even though it's simple.

DVK-1701 : Risk legend added to weather forecast

---

admin/src/components/form/SelectToggleSequenceDropdown.tsx

Bit of a complex solution, but sequence numbers are attached to fairway card's state so sorting 'options' array needs to be done based on 'selected' array

DVK-1656 - starting/ending fairways sort by sequence number

---

admin/src/components/form/SelectToggleSequenceDropdown.tsx
admin/src/components/form/SelectWithCustomDropdown.tsx
admin/src/utils/common.ts

Moved getSortedOptions function to common.ts, since now constructSelectDropdownLabel function is using it as well. Extra checks in constructSelectDropdownLabel, since logic for getting sorted options based on sequence number needs SelectedFairwayInput object.

fix/DVK-1656 - fix label of sequenced dropdown label

---

admin/src/components/form/SquatCalculationInput.tsx
src/components/content/Content.css
src/components/content/fairwayCard/FairwayCardContent.tsx
src/components/content/fairwayCard/SquatCalculationTemplate.css
src/components/content/fairwayCard/SquatCalculationTemplate.tsx
src/components/content/fairwayCard/SquatCalculationTemplateNotAvailable.tsx
src/graphql/fairwayCards.graphql
src/locales/en/translation.json
src/locales/fi/translation.json
src/locales/sv/translation.json

Squat calculation link is included if there are no linked templates for the card. If there are it will still show an empty page. This will be filled in DVK-1710

DVK-1715 : Added message and link to squat tab in DVK

---

src/components/popup/ForecastPopupContent.tsx

- Defined constant width for forecast content

DVK-1735 - forecast table width bug fix

---

cdk/lib/dvk-sonar-pipeline.ts

add admin tests and reports to pipeline

DVK-1706 admin tests to pipeline

---

src/components/mapOverlays/MapOverlays.tsx

updated documentation https://extranet.vayla.fi/wiki/display/DVKTP/DVK+Teknologia-arkkitehtuurikuva

remove ui console logging

---

cdk/lib/dvk-us-east.ts

action is count instead of block for now, replace later when verified to work ok

DVK-1691 rate-based waf limits to graphql 

---

admin/src/components/form/SelectInput.tsx
admin/src/components/form/SelectWithCustomDropdown.tsx
admin/src/components/form/SquatCalculationInput.tsx
admin/src/components/form/fairwayCard/SquatCalculationSection.tsx
admin/src/pages/MainPage.tsx
e2e/tests/admin/admin.spec.ts

Created a new test to create a new fairway card from an existing one that is N2000 type. Add a squat calculation with dummy values. Check that the card saves and then delete it to clean up. Updated all tests to have 60 second timeout

DVK-1731 : Include squat calculation in admin testing

---

admin/src/components/map/layerStyles/safetyEquipmentIcons.ts
admin/src/components/map/layerStyles/safetyEquipmentStyles.ts
src/components/content/SafetyEquipmentFaults.tsx
src/components/layerStyles/harborStyles.ts
src/components/layerStyles/safetyEquipmentIcons.ts
src/components/layerStyles/safetyEquipmentStyles.ts
src/components/layers.ts
src/components/popup/selectInteraction.ts

- Fixed sonarlint warnings
- Safety equipment icons separated to it's own file (admin and dvk)
- Default and selected restriction port icon getter is one function instead of two

DVK-1752 - fix sonarlint warnings from map styles

---

admin/src/components/form/SquatCalculationInput.tsx
admin/src/utils/formValidations.ts
admin/src/utils/reducers/fairwayCardSquatCalculationValidator.ts
cdk/graphql/schema.graphql

Same as other fields, so if one language version is non empty then the others should be too. Otherwise allows empty values

DVK-1762 : Make squat template additional info non-mandatory

---

cdk/lib/lambda/api/axios.ts
cdk/lib/lambda/environment.ts
cdk/lib/lambda/util.ts

Tested APIs through e.g. http://localhost:8080/api/featureloader?type=circle

DVK-1727 : Removed non-GeoJSON support for VATU API

---

e2e/tests/dvk/accessibility/accessibility.spec.ts

Added a checkup to ensure that layers menu has actually closed before running the next tests.

fix for main pages accessibility test

---

e2e/playwright.config.ts

Added back accidentally removed config file.

added back accidentally removed config file

---

cdk/lib/lambda/router/dvkRequestRouter.js
cdk/lib/squat-site.ts
root/maintenance.html

* add keyvalue store and maintenance page
* https://extranet.vayla.fi/wiki/display/DVKTP/Huoltokatkon+asettaminen

DVK-1728 huoltokatkosivu

---

admin/src/App.test.tsx
admin/src/components/FairwayCardForm.tsx
admin/src/components/form/SquatCalculationInput.tsx
admin/src/graphql/itemlist.graphql
admin/src/locales/en/translation.json
admin/src/locales/fi/translation.json
admin/src/locales/sv/translation.json
admin/src/pages/MainPage.tsx
admin/src/theme/dvk.css
admin/src/utils/common.test.ts
admin/src/utils/common.ts
admin/src/utils/squatCalculationUtils.test.ts
admin/src/utils/squatCalculationUtils.ts
cdk/graphql/schema.graphql
cdk/lib/lambda/graphql/query/fairwayCardsAndHarbors-handler.ts

Read the area list in the main page and insert the string in the notifications field.
Added squat calculations to GraphQL interface.
Created unit tests from common functions

DVK-1767 : Added missing area text into list
